server:
  port: 8001                                                       
  
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:7001/eureka
  instance:
    instance-id: microservicecloud-dept8001
    prefer-ip-address: true    

mybatis:
  config-location: classpath:mybatis/mybatis.cfg.xml              
  type-aliases-package: org.wangyu.springcloud.entity             
  mapper-locations:
  - classpath:mybatis/mapper/**/*.xml                             
  
spring:
  application:
    name: microservicecloud-dept                                  
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource                  
    driver-class-name: org.gjt.mm.mysql.Driver                    
    url: jdbc:mysql://127.0.0.1:3306/cloudDB01                    
    username: root
    password: 123456
    dbcp2:
      min-idle: 5                                                 
      initial-size: 5                                             
      max-total: 5                                                
      max-wait-millis: 200                                                      
      
info:
  app.name: org-mirroservicecloud
  company.name: org.wangyu.cn
  build.artifactId: $project.artfactId$
  build.version: 0.0.1-SNAPSHOT