server:
  port: 8003
  
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:7001/eureka/
  instance:
    instance-id: microservicecloud-dept8003
    prefer-ip-address: true
    
spring:
  application:
    name: microservicecloud-dept-consumer-8003